config/routes.rb
CelebheightRails::Application.routes.draw do

  root to: 'celebs#index'

  get 'celebs', to: redirect('/')

  get 'search', to: redirect('/')

  resources :celebs do
    get 'page/:page', :action => :index, :on => :collection
  end

  match 'search(/:q)(/:page)' => 'celebs#search', :constraints => { :q => /[0-9A-Za-z\-,%:()\.]+/ }

  resources :scans do

  end

end

app/models/celeb.rb
class Celeb < ActiveRecord::Base
  attr_accessible :first_name, :full_name, :last_name, :metric_height, :scanned, :twitter_id, :tweets, :slug, :description, :wiki_name
  attr_accessor :temp
  paginates_per 10

  mount_uploader :avatar, AvatarUploader

  extend FriendlyId
  friendly_id :full_name, use: :slugged

  def self.search(search)
    if search
      str   = URI.unescape(search)
      str = str.gsub('-', ' ')
      parts  = str.split(/\s*,\s*/)
      .map { |s| s.gsub(/[_%]/, '%' => '\\%', '_' => '\\_').strip }
      .map { |s| '%' + s.strip + '%' }

      where('full_name ilike any(array[?])', parts)

    else
      scoped
    end
  end

end

app/models/scan.rb
class Scan < ActiveRecord::Base
  attr_accessible :html, :last_scan, :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected
  unless Rails.application.config.consider_all_requests_local
    rescue_from Exception, with: lambda { |exception| render_error 500, exception }
    rescue_from ActionController::RoutingError, ActionController::UnknownController, ::AbstractController::ActionNotFound, ActiveRecord::RecordNotFound, with: lambda { |exception| render_error 404, exception }
  end

  private
  def render_error(status, exception)
    respond_to do |format|
      format.html { render template: "application/errors/error_#{status}", layout: 'layouts/application', status: status }
      format.all { render nothing: true, status: status }
    end
  end

end

app/controllers/celebs_controller.rb
class CelebsController < ApplicationController

  def search

    @celebs = Celeb.search(params[:q]).order('metric_height').page params[:page]

    @maximum = 0

    if !@celebs.blank?
      @maximum = Celeb.search(params[:q]).maximum("metric_height")
    end


    str = URI.unescape(params[:q]).gsub('-', ' ')

    parts = str.strip.split(/\s*,\s*/)

    parts.each do |item|
      customArray = item.split(/^(\w.+):([0-9]{1,7}(?:\.[0-9]{0,2})?)(\s?\w+)*$/i)

      #Rails.logger.debug("##############STR################: #{customArray}")

      customName = customArray[1].to_s.strip.titlecase
      customNumber = customArray[2].to_f
      customUnit = customArray[3].to_s.strip.downcase

      metricHeight = nil

      if customUnit == 'ft' || customUnit == 'feet' || customUnit == 'f'

        ftHeight = customNumber

        metricHeight = ftHeight * (0.3048/1)

      end

      if customUnit == 'meters' || customUnit == 'metres' || customUnit == 'm' || customUnit == 'cm' || customUnit == 'centimeters' || customUnit == 'centimetres'
        if customUnit == 'cm' || customUnit == 'centimeters' || customUnit == 'centimetres'
          metricHeight = customNumber / 100
        else
          metricHeight = customNumber
        end
      end

      if !metricHeight.nil?

        c = Celeb.new

        c.temp = true
        c.full_name = customName
        c.metric_height = metricHeight

        if(metricHeight > @maximum)
          @maximum = metricHeight
        end

        @celebs << c

      end

    end

    @search_str = ''

    if params[:q].blank? == false
      @search_str = params[:q].gsub('-', ' ');
    end

    Twitter.configure do |config|
      config.consumer_key = 'vaJajfUD2BEjX59tPLRog'
      config.consumer_secret = 'vjD8lIFLCW6okprtwWSj1iAnU54KT0oca7NV722nTw'
      config.oauth_token = '6074722-TtOZkdij4WgO25Rw3DIO1nYAZshYKh9qsB7S75IDg2'
      config.oauth_token_secret = 'a0jHGkLmBrpH6FeSQq2v2KytHTZ7hmtilHBIupFI'
    end

    @celebs.each do |celeb|
      # If we have a twitter id fetch tweets
      if celeb.twitter_id.blank? == false && (celeb.updated_at+1.days < DateTime.now || celeb.tweets.blank?)
        c = Celeb.find_or_initialize_by_full_name(celeb.full_name)
        uid = c.twitter_id
        c.tweets = Twitter.user_timeline(uid).to_json
        celeb.tweets = c.tweets
        c.save
      end
    end

    @celebs.sort! { |a,b| a.metric_height <=> b.metric_height }

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @celebs }
    end
  end

  # GET /celebs
  # GET /celebs.json
  def index

    # @celebs = Celeb.page params[:page]

    #respond_to do |format|
    #  format.html # index.html.erb
    #  format.json { render json: @celebs }
    #end
  end

  # GET /celebs/1
  # GET /celebs/1.json
  def show
    @celeb = Celeb.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @celeb }
    end
  end

  # GET /celebs/new
  # GET /celebs/new.json
  def new
    @celeb = Celeb.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @celeb }
    end
  end

  # GET /celebs/1/edit
  def edit
    @celeb = Celeb.find(params[:id])
  end

  # POST /celebs
  # POST /celebs.json
  def create
    @celeb = Celeb.new(params[:celeb])

    respond_to do |format|
      if @celeb.save
        format.html { redirect_to @celeb, notice: 'Celeb was successfully created.' }
        format.json { render json: @celeb, status: :created, location: @celeb }
      else
        format.html { render action: "new" }
        format.json { render json: @celeb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /celebs/1
  # PUT /celebs/1.json
  def update
    @celeb = Celeb.find(params[:id])

    respond_to do |format|
      if @celeb.update_attributes(params[:celeb])
        format.html { redirect_to @celeb, notice: 'Celeb was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @celeb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /celebs/1
  # DELETE /celebs/1.json
  def destroy
    @celeb = Celeb.find(params[:id])
    @celeb.destroy

    respond_to do |format|
      format.html { redirect_to celebs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/scans_controller.rb
class ScansController < ApplicationController

  # GET /scans
  # GET /scans.json
  def index
    @scans = Scan.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @scans }
    end
  end

  # GET /scans/1
  # GET /scans/1.json
  def show
    @scan = Scan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @scan }
    end
  end

  # GET /scans/new
  # GET /scans/new.json
  def new
    @scan = Scan.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @scan }
    end
  end

  # GET /scans/1/edit
  def edit
    @scan = Scan.find(params[:id])
  end

  # POST /scans
  # POST /scans.json
  def create
    @scan = Scan.new(params[:scan])

    respond_to do |format|
      if @scan.save
        format.html { redirect_to @scan, notice: 'Scan was successfully created.' }
        format.json { render json: @scan, status: :created, location: @scan }
      else
        format.html { render action: "new" }
        format.json { render json: @scan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /scans/1
  # PUT /scans/1.json
  def update
    @scan = Scan.find(params[:id])

    respond_to do |format|
      if @scan.update_attributes(params[:scan])
        format.html { redirect_to @scan, notice: 'Scan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @scan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scans/1
  # DELETE /scans/1.json
  def destroy
    @scan = Scan.find(params[:id])
    @scan.destroy

    respond_to do |format|
      format.html { redirect_to scans_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/celebs_helper.rb
module CelebsHelper
end

app/helpers/scan_source_helper.rb
module ScanSourceHelper
end

app/helpers/scans_helper.rb
module ScansHelper
end

app/views/celebs/_form.html.erb
<%= form_for(@celeb) do |f| %>
    <% if @celeb.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@celeb.errors.count, "error") %> prohibited this celeb from being saved:</h2>

          <ul>
            <% @celeb.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :first_name %><br />
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %><br />
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <%= f.label :full_name %><br />
      <%= f.text_field :full_name %>
    </div>

    <div class="field">
      <%= f.label :wiki_name %><br />
      <%= f.text_field :wiki_name %>
    </div>

    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_area :description %>
    </div>

    <div class="field">
      <%= f.label :avatar %><br />
      <%= image_tag(@celeb.avatar_url) if @celeb.avatar? %><br />
      <%= f.file_field :avatar %>
    </div>

    <div class="field">
      <%= f.label :metric_height %><br />
      <%= f.text_field :metric_height %>
    </div>

    <div class="field">
      <%= f.label :twitter_id %><br />
      <%= f.text_field :twitter_id %>
    </div>

    <div class="field">
      <%= f.label :scanned %><br />
      <%= f.check_box :scanned %>
    </div>



    <div class="actions">
      <%= f.submit %>
    </div>

<% end %>

app/views/celebs/_searchForm.html.erb
<div class="celebs-search well">
  <form class="celebs-search--form form-horizontal" role="form" method="GET" action="/search" data-jsonaction="/search.json">
    <div class="input-append">
      <input type="text" name="q" id="celebs-search-input" class="celebs-search--name form-control" placeholder="Celebrity Name" value="<%= @search_str %>">
      <button type="submit" class="btn"><i class="glyphicon glyphicon-search"></i></button>
    </div>
  </form>
</div>

app/views/celebs/edit.html.erb
<h1>Editing celeb</h1>

<%= render 'form' %>

<%= link_to 'Show', @celeb %> |
<%= link_to 'Back', celebs_path %>

app/views/celebs/index.html.erb
<div id="wrap" class="row stage">

  <%= render 'searchForm' %>

  <div id="content" class="celebresults clearfix stage"></div>

</div>

app/views/celebs/new.html.erb
<h1>New celeb</h1>

<%= render 'form' %>

<%= link_to 'Back', celebs_path %>

app/views/celebs/search.html.erb
<div id="wrap" class="row stage">
  <div class="fadeleft"></div>
  <div class="faderight"></div>
  <%= render 'searchForm' %>

  <div id="content" class="celebresults clearfix stage" data-maximum="<%= @maximum %>">

    <div class="celebresults--pagination">
      <%= paginate @celebs %>
    </div>

    <% if @celebs.blank? %>
        <div class="panel panel-warning">
          <div class="panel-body clearfix">
            <div class="celebitem__empty">No celebs found</div>
          </div>
        </div>
    <% else %>
        <div class="clearfix">
          <% @celebs.each do |celeb| %>
              <div class="celebitem" data-scale="<%= number_with_precision(celeb.metric_height, precision: 3, significant: true) %>" data-content="<%= celeb.description %>">
                <div class="celebitem--heading">
                  <h2 class="celebitem--fullname">
                    <%if celeb.temp.blank? %>
                        <%= link_to celeb.full_name, celeb %>
                    <% else %>
                        <%= celeb.full_name =%>
                    <% end %>
                    <span class="celebitem--metawrap"><span class="celebitem--metricheight"><%= number_with_precision(celeb.metric_height, precision: 3, significant: true) %> m</span>&nbsp;&harr;&nbsp;<span class="celebitem--impheight"><%= number_with_precision(((celeb.metric_height / 0.3048 * 100) * 0.01), precision: 2, significant: true) %> ft<span></span></span>
                  </h2>
                </div>
                <div class="panel-body clearfix">
                  <div class="celebitem--image">
                    <img class="img-circle img-responsive" src="<%= celeb.avatar.thumb.url %>" alt="<%= celeb.first_name %>" width="70" height="70">
                  </div>
                </div>
              </div>
          <% end %>
        </div>
    <% end %>
  </div>

</div>

app/views/celebs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Firstname:</b>
  <%= @celeb.first_name %>
</p>

<p>
  <b>Lastname:</b>
  <%= @celeb.last_name %>
</p>

<p>
  <b>Fullname:</b>
  <%= @celeb.full_name %>
</p>

<p>
  <b>Metricheight:</b>
  <%= @celeb.metric_height %>
</p>

<p>
  <b>Twitter ID:</b>
  <%= @celeb.twitter_id %>
</p>

<p>
  <b>Tweets:</b>
  <%= @celeb.tweets %>
</p>


<%= link_to 'Edit', edit_celeb_path(@celeb) %> |
<%= link_to 'Back', celebs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html lang="en">
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Celeb Heights</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <meta name="viewport" content="initial-scale=1.0, width=device-width, user-scalable=no">
  <%= csrf_meta_tags %>
</head>
<body>
<!--[if lt IE 7]>
<p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->
<div class="container stage">
    <%= yield %>
</div>
</body>
</html>

app/views/scans/_form.html.erb
<%= form_for(@scan) do |f| %>
  <% if @scan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scan.errors.count, "error") %> prohibited this scan from being saved:</h2>

      <ul>
      <% @scan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :html %><br />
    <%= f.text_area :html %>
  </div>
  <div class="field">
    <%= f.label :last_scan %><br />
    <%= f.datetime_select :last_scan %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scans/edit.html.erb
<h1>Editing scan</h1>

<%= render 'form' %>

<%= link_to 'Show', @scan %> |
<%= link_to 'Back', scans_path %>

app/views/scans/index.html.erb
<h1>Listing scans</h1>

<table>
  <tr>
    <th>Html</th>
    <th>Last scan</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @scans.each do |scan| %>
  <tr>
    <td><%= scan.html %></td>
    <td><%= scan.last_scan %></td>
    <td><%= scan.url %></td>
    <td><%= link_to 'Show', scan %></td>
    <td><%= link_to 'Edit', edit_scan_path(scan) %></td>
    <td><%= link_to 'Destroy', scan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Scan', new_scan_path %>

app/views/scans/new.html.erb
<h1>New scan</h1>

<%= render 'form' %>

<%= link_to 'Back', scans_path %>

app/views/scans/scan.html.erb
<%= debug(@colleciton) %>

app/views/scans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Html:</b>
  <%= @scan.html %>
</p>

<p>
  <b>Last scan:</b>
  <%= @scan.last_scan %>
</p>

<p>
  <b>Url:</b>
  <%= @scan.url %>
</p>


<%= link_to 'Edit', edit_scan_path(@scan) %> |
<%= link_to 'Back', scans_path %>